name: Запрос фунционала / Feature request
title: "[Feature] "
description: Предложите новый функционал / Propose your feature request

body:
  - type: markdown
    attributes:
      value: |
        ## Прежде чем создавать проблему, убедитесь в следующем:
        1. Обязательно укажите краткий и понятный заголовок, чтобы другим было проще найти вашу проблему.
        2. Убедитесь, что похожая проблема ещё не создана в разделе [существующих проблем](https://github.com/pluralplay/FlClashX/issues?q=is%3Aissue), иначе обсудите свой вопрос там.
        3. Опишите проблему подробно и по шаблону, иначе заявка будет закрыта без рассмотрения.
        ## Before submitting the issue, please make sure of the following checklist:
        1. Please be sure to fill in a concise and clear title for the issue so that others can quickly search
        2. Please make sure there is no similar issue in the [existing issues](https://github.com/pluralplay/FlClashX/issues?q=is%3Aissue), otherwise please discuss under the existing issue
        3. Please describe the problem in detail according to the template specification, otherwise issue will be closed directly.

  - type: textarea
    id: description
    attributes:
      label: Описание фунции / Feature description
      description: Четкое и краткое описание функции / A clear and concise description of what the feature is
    validations:
      required: true
  - type: textarea
    attributes:
      label: Сценарий использования / Use case
      description: Пожалуйста, опишите сценарий использования вашего запроса на функцию / Please describe the use case of your feature request
    validations:
      required: true
  - type: checkboxes
    id: os-labels
    attributes:
      label: Операционная система / Target OS
      description: Пожалуйста, выберите операционную систему(ы), для которых предназначена эта функция (выберите минимум одну) / Please select the operating system(s) for this feature request (select at least one)
      options:
        - label: Android
        - label: Windows
        - label: MacOS
        - label: Linux
    validations:
      required: true
